### ISSUE TITLE
[testActionRecognitionLib] add tests that return known discrepancies

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/xgnitive#2]
[testActionRecognitionLib] add tests that return known discrepancies:
- [x] 0 (for identical inputs).
- [x] a simple case where the discrepancy can be calculated by hand.

**Comment by RaulFdzbis** [comment]
This issue can be considered closed with [ b9cdf4e](https://github.com/roboticslab-uc3m/xgnitive/commit/b9cdf4e541656a23ac2e01145be864167faa295d).
