### ISSUE TITLE
Document programs, libraries and apps

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/xgnitive#25]
The contents should match in quantity:
- [x] https://github.com/roboticslab-uc3m/xgnitive/tree/develop/programs vs http://robots.uc3m.es/dox-xgnitive/group__xgnitive__programs.html
- [x] https://github.com/roboticslab-uc3m/xgnitive/tree/develop/libraries vs http://robots.uc3m.es/dox-xgnitive/group__xgnitive__libraries.html
- [x] https://github.com/roboticslab-uc3m/xgnitive/tree/issue-22-yarpmanager-xml/share vs http://robots.uc3m.es/dox-xgnitive/group__xgnitive__applications.html

**Comment by RaulFdzbis** [comment]
Finished in 88c1179a709f312b187e5b00a30bf14f99449ed2 , should we close it? Or let it open to start documenting classes, functions...?

**Comment by jgvictores** [comment]
@RaulFdzbis It's looking really good, I'm closing the issue, thanks!!!
