### ISSUE TITLE
Think about ICRA2018

### ISSUE THREAD

**Issue by RaulFdzbis** [roboticslab-uc3m/xgnitive#27]
![220px-kangaroo_and_joey03](https://cloud.githubusercontent.com/assets/6704441/23655134/1aec04a2-0334-11e7-8a18-aca8f07c566b.jpg)

**Comment by David-Estevez** [comment]
http://tinyurl.com/z38rl7r

**Comment by RaulFdzbis** [comment]
Proposed by @jgvictores for CGDA development:
plan a: rl (no drl)
plan b: pga

**Comment by jgvictores** [comment]
Deadline past, papers sent.
Time to stop Thinking about ICRA2018.
