### ISSUE TITLE
FYI: Now we are able to create walls with small pixels

### ISSUE THREAD

**Issue by RaulFdzbis** [roboticslab-uc3m/xgnitive#45]
Thx to [this](https://github.com/roboticslab-uc3m/xgnitive/blob/ca0996cdbb10b3d15b5d75dd11b98c9a701dbfba/scripts/wall_creator.py).

**Comment by jgvictores** [comment]
Great! Leaving open till moved to `programs`.

**Comment by RaulFdzbis** [comment]
Updated! :haircut_man:
