### ISSUE TITLE
How-to paintSquaresOnScreen

### ISSUE THREAD

**Issue by RaulFdzbis** [roboticslab-uc3m/xgnitive#49]
[How-to paintSquaresOnScreen](https://github.com/roboticslab-uc3m/xgnitive/blob/real-tv/programs/paintSquaresOnScreen/README.md)

Update: Better in real-tv branch

**Comment by RaulFdzbis** [comment]
So I think this tries to say to document How-to paintSquaresOnScreen using the real tv?

@jgvictores what do you think? jajaj

**Comment by jgvictores** [comment]
Yeah, the [current README](https://github.com/roboticslab-uc3m/xgnitive/blob/10b65ed9d8900fc0b06ef3bac002703fe4bf6085/programs/paintSquaresOnScreen/README.md) in `develop` is pretty empty. Just basic launch docs.

**Comment by RaulFdzbis** [comment]
Some work done in https://github.com/roboticslab-uc3m/xgnitive/commit/ddc961f0edc4f85f788a4d8315e21732fa4bce66

**Comment by jgvictores** [comment]
Nice, thanks!
On my behalf, it's okay to close this issue.

**Comment by RaulFdzbis** [comment]
Cool!
