### ISSUE TITLE
Paint demonstrations

### ISSUE THREAD

**Issue by RaulFdzbis** [roboticslab-uc3m/xgnitive#52]
Paint demonstrations. Steps:
- [x] launchManipulation
- [ ] gcmp (review (update, install, understand) k-d for this)
- [ ] follow recommendations of https://github.com/roboticslab-uc3m/developer-manual/blob/master/frequently-asked-questions.md#how-can-i-record-data-for-programming-by-demonstration-pbd-aka-learning-from-demonstration-lfd
- [ ] Store at: http://asrob.uc3m.es/svn/ASROBrepo/Personal/research/datasets/xgnitiveDatasets/

**Comment by RaulFdzbis** [comment]
Updated steps in description.

**Comment by RaulFdzbis** [comment]
> gcmp (review (update, install, understand) k-d for this)

We are going to try to do k-d gcmp directly on TEO-manipulation as a first approach.

**Comment by jgvictores** [comment]
Not all drivers act in torque mode with launchManipulation + gcmp. I've opened https://github.com/roboticslab-uc3m/teo-main/issues/35 to track this.

**Comment by jgvictores** [comment]
Also https://github.com/roboticslab-uc3m/teo-hardware-issues/issues/14 blocks

**Comment by jgvictores** [comment]
Closing as `invalid`, description was very vague regarding motivation/target.
