### ISSUE TITLE
[cmake] Create FindECF.cmake

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/xgnitive#6]
If [ECF](http://ecf.zemris.fer.hr/) is going to be fixed as a dependency:
- [x] Create a FindECF.cmake
- [x] Update the CMakeLists.txt of the programs and/or libraries that use it

**Comment by RaulFdzbis** [comment]
This [ commit ](https://github.com/roboticslab-uc3m/xgnitive/commit/c423079bb3cfed487a1b7250170dcf8f825e5165) implements a working FindECF.cmake file for the project.  
@jgvictores can you check it?.

**Comment by RaulFdzbis** [comment]
This [commit](https://github.com/roboticslab-uc3m/xgnitive/commit/5fa433d256dd65b2f26ead37ce3efd72fae09c02) add the new library **EcfComponents** to the xgnitive repository. 

This library uses the ECF external library. The CMakeLists files were generated using the FindECF.cmake

**Comment by jgvictores** [comment]
FindECF.cmake looks good!
Maybe you could edit Aquila out of the commented lines too. ;-)

**Comment by RaulFdzbis** [comment]
[Done](https://github.com/roboticslab-uc3m/xgnitive/commit/84bd072ecb78657302c34020227741d705820139)!

**Comment by jgvictores** [comment]
@RaulFdzbis Any reason this was reopened?

**Comment by RaulFdzbis** [comment]
I dont see any. You are right, lets close it :sunglasses:
